index:
  path: /
  controller: App\Controller\DefaultController::index
# config/routes/dev/framework.yaml
_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix:   /_error